package com.project1.dao;

import com.project1.dataobject.ModifyfileDO;

public interface ModifyfileDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modify_file
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modify_file
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insert(ModifyfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modify_file
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insertSelective(ModifyfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modify_file
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    ModifyfileDO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modify_file
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKeySelective(ModifyfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modify_file
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKey(ModifyfileDO record);
}