package com.project1.dao;

import com.project1.dataobject.modifyfileDO;

public interface modifyfileDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modify_file
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modify_file
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insert(modifyfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modify_file
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insertSelective(modifyfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modify_file
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    modifyfileDO selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modify_file
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKeySelective(modifyfileDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table modify_file
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKey(modifyfileDO record);
}