package com.project1.dao;

import com.project1.dataobject.RolepermitinfoDO;

public interface RolepermitinfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int deleteByPrimaryKey(String permitStr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insert(RolepermitinfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insertSelective(RolepermitinfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    RolepermitinfoDO selectByPrimaryKey(String permitStr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKeySelective(RolepermitinfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKey(RolepermitinfoDO record);
}