package com.project1.dao;

import com.project1.dataobject.rolepermitDO;

import java.util.Set;

public interface rolepermitDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int deleteByPrimaryKey(Integer permitNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insert(rolepermitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insertSelective(rolepermitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    rolepermitDO selectByPrimaryKey(Integer permitNo);

    Set<rolepermitDO> selectByRoldId(String role_id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKeySelective(rolepermitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKey(rolepermitDO record);
}