package com.project1.dao;

import com.project1.dataobject.RolepermitDO;

import java.util.Set;

public interface RolepermitDOMapper {

    int deleteByRoleId(String role_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int deleteByPrimaryKey(Integer permitNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insert(RolepermitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insertSelective(RolepermitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    RolepermitDO selectByPrimaryKey(Integer permitNo);

    Set<RolepermitDO> selectByRoldId(String role_id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKeySelective(RolepermitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKey(RolepermitDO record);
}