package com.project1.dao;

import com.project1.dataobject.rolepermitinfoDO;

public interface rolepermitinfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int deleteByPrimaryKey(String permitStr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insert(rolepermitinfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insertSelective(rolepermitinfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    rolepermitinfoDO selectByPrimaryKey(String permitStr);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKeySelective(rolepermitinfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKey(rolepermitinfoDO record);
}