package com.project1.dao;

import com.project1.dataobject.UserunitDO;

public interface UserunitDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_unit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int deleteByPrimaryKey(Integer unitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_unit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insert(UserunitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_unit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insertSelective(UserunitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_unit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    UserunitDO selectByPrimaryKey(Integer unitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_unit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKeySelective(UserunitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_unit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKey(UserunitDO record);
}