package com.project1.dao;

import com.project1.dataobject.userresumeDO;

import java.util.List;

public interface userresumeDOMapper {

    List<userresumeDO> selectResumeById(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Mon May 06 15:41:40 CST 2019
     */
    int deleteByPrimaryKey(Integer resumeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Mon May 06 15:41:40 CST 2019
     */
    int insert(userresumeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Mon May 06 15:41:40 CST 2019
     */
    int insertSelective(userresumeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Mon May 06 15:41:40 CST 2019
     */
    userresumeDO selectByPrimaryKey(Integer resumeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Mon May 06 15:41:40 CST 2019
     */
    int updateByPrimaryKeySelective(userresumeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Mon May 06 15:41:40 CST 2019
     */
    int updateByPrimaryKey(userresumeDO record);
}