package com.project1.dao;

import com.project1.dataobject.UserpermitDO;

public interface UserpermitDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int deleteByPrimaryKey(Integer permitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insert(UserpermitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insertSelective(UserpermitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    UserpermitDO selectByPrimaryKey(Integer permitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKeySelective(UserpermitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKey(UserpermitDO record);
}