package com.project1.dao;

import com.project1.dataobject.UserresumeDO;

import java.util.List;

public interface UserresumeDOMapper {

    List<UserresumeDO> selectResumeById(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Mon May 06 15:41:40 CST 2019
     */
    int deleteByPrimaryKey(Integer resumeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Mon May 06 15:41:40 CST 2019
     */
    int insert(UserresumeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Mon May 06 15:41:40 CST 2019
     */
    int insertSelective(UserresumeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Mon May 06 15:41:40 CST 2019
     */
    UserresumeDO selectByPrimaryKey(Integer resumeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Mon May 06 15:41:40 CST 2019
     */
    int updateByPrimaryKeySelective(UserresumeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Mon May 06 15:41:40 CST 2019
     */
    int updateByPrimaryKey(UserresumeDO record);
}