package com.project1.dao;

import com.project1.dataobject.UsertypeworkDO;

public interface UsertypeworkDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_typework
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int deleteByPrimaryKey(Integer wordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_typework
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insert(UsertypeworkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_typework
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insertSelective(UsertypeworkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_typework
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    UsertypeworkDO selectByPrimaryKey(Integer wordId);
    UsertypeworkDO selectBywordName(String word);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_typework
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKeySelective(UsertypeworkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_typework
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKey(UsertypeworkDO record);
}