package com.project1.dao;

import com.project1.dataobject.usertypeworkDO;

public interface usertypeworkDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_typework
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int deleteByPrimaryKey(Integer wordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_typework
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insert(usertypeworkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_typework
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insertSelective(usertypeworkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_typework
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    usertypeworkDO selectByPrimaryKey(Integer wordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_typework
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKeySelective(usertypeworkDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_typework
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKey(usertypeworkDO record);
}