package com.project1.dao;

import com.project1.dataobject.userpermitDO;

public interface userpermitDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int deleteByPrimaryKey(Integer permitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insert(userpermitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int insertSelective(userpermitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    userpermitDO selectByPrimaryKey(Integer permitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKeySelective(userpermitDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_permit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    int updateByPrimaryKey(userpermitDO record);
}