package com.project1.dao;

import com.project1.dataobject.UserroleDO;

public interface UserroleDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 11 09:58:06 CST 2019
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 11 09:58:06 CST 2019
     */
    int insert(UserroleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 11 09:58:06 CST 2019
     */
    int insertSelective(UserroleDO record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 11 09:58:06 CST 2019
     */
    UserroleDO selectByPrimaryKey(Integer roleId);
    UserroleDO selectByRoleName(String roleName);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 11 09:58:06 CST 2019
     */
    int updateByPrimaryKeySelective(UserroleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbg.generated Sat May 11 09:58:06 CST 2019
     */
    int updateByPrimaryKey(UserroleDO record);
}