package com.project1.dao;

import com.project1.dataobject.userresumeDO;

public interface userresumeDOMapper {

    userresumeDO selectuserByid(Integer user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Thu May 02 10:13:39 CST 2019
     */
    int deleteByPrimaryKey(Integer resumeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Thu May 02 10:13:39 CST 2019
     */
    int insert(userresumeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Thu May 02 10:13:39 CST 2019
     */
    int insertSelective(userresumeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Thu May 02 10:13:39 CST 2019
     */
    userresumeDO selectByPrimaryKey(Integer resumeNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Thu May 02 10:13:39 CST 2019
     */
    int updateByPrimaryKeySelective(userresumeDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_resume
     *
     * @mbg.generated Thu May 02 10:13:39 CST 2019
     */
    int updateByPrimaryKey(userresumeDO record);
}