package com.project1.dataobject;

import java.util.Date;

public class modifyfileDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modify_file.user_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modify_file.event
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String event;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column modify_file.time
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_file.user_id
     *
     * @return the value of modify_file.user_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_file.user_id
     *
     * @param userId the value for modify_file.user_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_file.event
     *
     * @return the value of modify_file.event
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_file.event
     *
     * @param event the value for modify_file.event
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column modify_file.time
     *
     * @return the value of modify_file.time
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column modify_file.time
     *
     * @param time the value for modify_file.time
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }
}