package com.project1.dataobject;

public class RolepermitinfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permit_info.permit_str
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String permitStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permit_info.permit_name
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String permitName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permit_info.permit_str
     *
     * @return the value of role_permit_info.permit_str
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getPermitStr() {
        return permitStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permit_info.permit_str
     *
     * @param permitStr the value for role_permit_info.permit_str
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setPermitStr(String permitStr) {
        this.permitStr = permitStr == null ? null : permitStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permit_info.permit_name
     *
     * @return the value of role_permit_info.permit_name
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getPermitName() {
        return permitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permit_info.permit_name
     *
     * @param permitName the value for role_permit_info.permit_name
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setPermitName(String permitName) {
        this.permitName = permitName == null ? null : permitName.trim();
    }
}