package com.project1.dataobject;

public class RolepermitDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permit.permit_no
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private Integer permitNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permit.role_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permit.permit_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String permitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_permit.right_type
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private Integer rightType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permit.permit_no
     *
     * @return the value of role_permit.permit_no
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public Integer getPermitNo() {
        return permitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permit.permit_no
     *
     * @param permitNo the value for role_permit.permit_no
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setPermitNo(Integer permitNo) {
        this.permitNo = permitNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permit.role_id
     *
     * @return the value of role_permit.role_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permit.role_id
     *
     * @param roleId the value for role_permit.role_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permit.permit_id
     *
     * @return the value of role_permit.permit_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getPermitId() {
        return permitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permit.permit_id
     *
     * @param permitId the value for role_permit.permit_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setPermitId(String permitId) {
        this.permitId = permitId == null ? null : permitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_permit.right_type
     *
     * @return the value of role_permit.right_type
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public Integer getRightType() {
        return rightType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_permit.right_type
     *
     * @param rightType the value for role_permit.right_type
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setRightType(Integer rightType) {
        this.rightType = rightType;
    }
}