package com.project1.dataobject;

import java.util.HashSet;
import java.util.Set;

public class userroleDO {


    private Set<userinfoDO> userinfoDOS = new HashSet<>();

    private Set<userpermitDO> userpermitDOS = new HashSet<>();

    public Set<userinfoDO> getUserinfoDOS() {
        return userinfoDOS;
    }

    public void setUserinfoDOS(Set<userinfoDO> userinfoDOS) {
        this.userinfoDOS = userinfoDOS;
    }

    public Set<userpermitDO> getUserpermitDOS() {
        return userpermitDOS;
    }

    public void setUserpermitDOS(Set<userpermitDO> userpermitDOS) {
        this.userpermitDOS = userpermitDOS;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role_name
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role.role_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String roleInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.role_id
     *
     * @return the value of user_role.role_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.role_id
     *
     * @param roleId the value for user_role.role_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.role_name
     *
     * @return the value of user_role.role_name
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.role_name
     *
     * @param roleName the value for user_role.role_name
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role.role_info
     *
     * @return the value of user_role.role_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getRoleInfo() {
        return roleInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role.role_info
     *
     * @param roleInfo the value for user_role.role_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setRoleInfo(String roleInfo) {
        this.roleInfo = roleInfo == null ? null : roleInfo.trim();
    }
}