package com.project1.dataobject;

public class userroleinfoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_info.role_no
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private Integer roleNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_info.user_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_info.role_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_info.role_no
     *
     * @return the value of user_role_info.role_no
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public Integer getRoleNo() {
        return roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_info.role_no
     *
     * @param roleNo the value for user_role_info.role_no
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setRoleNo(Integer roleNo) {
        this.roleNo = roleNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_info.user_id
     *
     * @return the value of user_role_info.user_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_info.user_id
     *
     * @param userId the value for user_role_info.user_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_info.role_id
     *
     * @return the value of user_role_info.role_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_info.role_id
     *
     * @param roleId the value for user_role_info.role_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}