package com.project1.dataobject;

import com.project1.service.model.RoleModel;

import java.util.HashSet;
import java.util.Set;

public class userinfoDO {


    private Set<userroleDO> userroleDOS = new HashSet<>();

    public Set<userroleDO> getUserroleDOS() {
        return userroleDOS;
    }

    public void setUserroleDOS(Set<userroleDO> userroleDOS) {
        this.userroleDOS = userroleDOS;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.unit_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birthday
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.nation
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String nation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.education
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.political_status
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String politicalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.word_time
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String wordTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.end_time
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.work_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String workId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.wage
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private Integer wage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.zip_code
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.home_address
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String homeAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String phone;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_id
     *
     * @return the value of user_info.user_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_id
     *
     * @param userId the value for user_info.user_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.unit_id
     *
     * @return the value of user_info.unit_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.unit_id
     *
     * @param unitId the value for user_info.unit_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setUnitId(String unitId) {
        this.unitId = unitId == null ? null : unitId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birthday
     *
     * @return the value of user_info.birthday
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birthday
     *
     * @param birthday the value for user_info.birthday
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.nation
     *
     * @return the value of user_info.nation
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.nation
     *
     * @param nation the value for user_info.nation
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.education
     *
     * @return the value of user_info.education
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.education
     *
     * @param education the value for user_info.education
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.political_status
     *
     * @return the value of user_info.political_status
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getPoliticalStatus() {
        return politicalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.political_status
     *
     * @param politicalStatus the value for user_info.political_status
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setPoliticalStatus(String politicalStatus) {
        this.politicalStatus = politicalStatus == null ? null : politicalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.word_time
     *
     * @return the value of user_info.word_time
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getWordTime() {
        return wordTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.word_time
     *
     * @param wordTime the value for user_info.word_time
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setWordTime(String wordTime) {
        this.wordTime = wordTime == null ? null : wordTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.end_time
     *
     * @return the value of user_info.end_time
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.end_time
     *
     * @param endTime the value for user_info.end_time
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.work_id
     *
     * @return the value of user_info.work_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.work_id
     *
     * @param workId the value for user_info.work_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setWorkId(String workId) {
        this.workId = workId == null ? null : workId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.wage
     *
     * @return the value of user_info.wage
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public Integer getWage() {
        return wage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.wage
     *
     * @param wage the value for user_info.wage
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setWage(Integer wage) {
        this.wage = wage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.zip_code
     *
     * @return the value of user_info.zip_code
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.zip_code
     *
     * @param zipCode the value for user_info.zip_code
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.home_address
     *
     * @return the value of user_info.home_address
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.home_address
     *
     * @param homeAddress the value for user_info.home_address
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone
     *
     * @return the value of user_info.phone
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone
     *
     * @param phone the value for user_info.phone
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}