package com.project1.dataobject;

import java.util.HashSet;
import java.util.Set;

public class UserpermitDO {


    private Set<UserroleDO> UserroleDOS = new HashSet<>();

    public Set<UserroleDO> getUserroleDOS() {
        return UserroleDOS;
    }

    public void setUserroleDOS(Set<UserroleDO> UserroleDOS) {
        this.UserroleDOS = UserroleDOS;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permit.permit_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private Integer permitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permit.permit_name
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String permitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_permit.permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String permitInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permit.permit_id
     *
     * @return the value of user_permit.permit_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public Integer getPermitId() {
        return permitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permit.permit_id
     *
     * @param permitId the value for user_permit.permit_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setPermitId(Integer permitId) {
        this.permitId = permitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permit.permit_name
     *
     * @return the value of user_permit.permit_name
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getPermitName() {
        return permitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permit.permit_name
     *
     * @param permitName the value for user_permit.permit_name
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setPermitName(String permitName) {
        this.permitName = permitName == null ? null : permitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_permit.permit_info
     *
     * @return the value of user_permit.permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getPermitInfo() {
        return permitInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_permit.permit_info
     *
     * @param permitInfo the value for user_permit.permit_info
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setPermitInfo(String permitInfo) {
        this.permitInfo = permitInfo == null ? null : permitInfo.trim();
    }
}