package com.project1.dataobject;

public class UserunitDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_unit.unit_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private Integer unitId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_unit.unit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    private String unit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_unit.unit_id
     *
     * @return the value of user_unit.unit_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_unit.unit_id
     *
     * @param unitId the value for user_unit.unit_id
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_unit.unit
     *
     * @return the value of user_unit.unit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_unit.unit
     *
     * @param unit the value for user_unit.unit
     *
     * @mbg.generated Tue Apr 23 09:17:39 CST 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }
}