package com.project1.dataobject;

public class userresumeDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resume.resume_no
     *
     * @mbg.generated Mon May 06 15:47:13 CST 2019
     */
    private Integer resumeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resume.id
     *
     * @mbg.generated Mon May 06 15:47:13 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resume.edate
     *
     * @mbg.generated Mon May 06 15:47:13 CST 2019
     */
    private String edate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_resume.event
     *
     * @mbg.generated Mon May 06 15:47:13 CST 2019
     */
    private String event;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resume.resume_no
     *
     * @return the value of user_resume.resume_no
     *
     * @mbg.generated Mon May 06 15:47:13 CST 2019
     */
    public Integer getResumeNo() {
        return resumeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resume.resume_no
     *
     * @param resumeNo the value for user_resume.resume_no
     *
     * @mbg.generated Mon May 06 15:47:13 CST 2019
     */
    public void setResumeNo(Integer resumeNo) {
        this.resumeNo = resumeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resume.id
     *
     * @return the value of user_resume.id
     *
     * @mbg.generated Mon May 06 15:47:13 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resume.id
     *
     * @param id the value for user_resume.id
     *
     * @mbg.generated Mon May 06 15:47:13 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resume.edate
     *
     * @return the value of user_resume.edate
     *
     * @mbg.generated Mon May 06 15:47:13 CST 2019
     */
    public String getEdate() {
        return edate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resume.edate
     *
     * @param edate the value for user_resume.edate
     *
     * @mbg.generated Mon May 06 15:47:13 CST 2019
     */
    public void setEdate(String edate) {
        this.edate = edate == null ? null : edate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_resume.event
     *
     * @return the value of user_resume.event
     *
     * @mbg.generated Mon May 06 15:47:13 CST 2019
     */
    public String getEvent() {
        return event;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_resume.event
     *
     * @param event the value for user_resume.event
     *
     * @mbg.generated Mon May 06 15:47:13 CST 2019
     */
    public void setEvent(String event) {
        this.event = event == null ? null : event.trim();
    }
}